### PR TITLE
Fix build script and add paket.template for publishing

### PR DESCRIPTION
**Pull request by ascjones**
Hope you don't mind, but I pushed this to nuget.org so I could use it:

https://www.nuget.org/packages/Fuchu.Xunit/

Let me know and happy to transfer ownership (or take it down).

### CODE REVIEW

**Comment by fsoikin** [comment]
Hi.
Wow.
I was going to push it to Nuget at some point, but I never thought it would actually be useful to someone else, that's why I took so long.

Thank you very much for the PR, and yes, I will gladly assume the ownership.

**Comment by ascjones** [comment]
Cool, I just need your nuget username to add you as an owner.

I've made a couple more changes (relaxing dependency constraints a bit), will do another PR for that when I've got it to work.

Thanks for making the library!

**Comment by fsoikin** [comment]
The account name is [erecruit](https://www.nuget.org/profiles/erecruit).
You're welcome :-)

**Comment by ascjones** [comment]
Added you as an owner...feel free to remove me once you're approved.

I've also relaxed the package version constraints a bit to make it work with other dependencies - I will send a PR.

**Comment by fsoikin** [comment]
Thank you, got the ownership. I will hold off on kicking you out just yet, before I get down the automation for publishing the package.

**Pull request merged**
